puts "✅ Creating guides users"
romain = User.create!(first_name: "Romain", last_name: "Géricot", password: "azerty", role: 0, description: "I lived all around the world, come to discorver it with me", email: "romain@gmail.com")
jerome = User.create!(first_name: "Jérôme", last_name: "Toulouse", password: "azerty", role: 0, description: "Ask me everything you need about colors, forms and CSS .... but never about bootstrap", email: "jerome@gmail.com")
edouard = User.create!(first_name: "Edouard", last_name: "Couten", password: "azerty", role:0, description: "If you want to play tennis, call me!", email: "edouard@gmail.com")
fabiola = User.create!(first_name: "Fabiola", last_name: "Camargo", password: "azerty", role: 0, description: "If you want to eat come with me", email: "fabiola@gmail.com")
nicolas = User.create!(first_name: "Nicolas", last_name: "Le wagon", password: "azerty", role: 0, description: "Quand je ne suis pas sur le bassin à admirer les magnifiques couchers de soleil de Pereire, vous me trouverez dans ma ville natale Bordeaux surtout dans le vieux quartier, place du palais ou rue St James avec un bon verre de vin.Je vis maintenant à Gujan-Mestras au pied du bassin d'Arcachon, une région magnifique, incontournable si vous êtes en visite sur Bordeaux.Je vous invite à une traversée saharienne sur les crêtes de la dune du Pilat d’où la vue est juste extraordinaire. Venez apprendre sa formation lente mais riche en occupation humaine à travers les siècles.Arcachon, c'est surtout son quartier historique de la ville d’hiver aux villas luxueuses dissimulées sous les pins. Vous y découvrirez différents styles architecturaux du néo-classique, suisse (tendance chalet), écossais (tendance manoir) et j'en passe. Dans le domaine du vin, je conduis en bus ou à pied des wine tours dans les régions viticoles de Bordeaux. Je commente entre autres le travail de la vigne, les cépages, les arômes, les maladies, la notion de Bio et Biodynamie, l’histoire du vignoble Bordelais, les propriétés, les effets du réchauffement sur le vin. J’ai bénéficié d’une formation au CIVB qui me permet de parler du Vin avec aisance; maîtriser les accords mets et vins, savoir conseiller mes clients.", email: "nicolas@gmail.com")

puts "✅ Creating user"
jojo = User.create!(first_name: "Jonathan", last_name: "Serafini", password: "azerty", role: 1, description: "I want to travel again!!!", email: "jonathan@gmail.com")

puts "✅ Creating tours"

